# -*- coding: utf-8 -*-
"""AI Conference Hack Day - Weaviate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pjQbZCJ2CrJ6aOX_hN37l3Q7u_fhtf0

# AI Conference Hack Day - Sept 16, 2025
## Weaviate Notebook

---



![Image](https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=2,background=white,quality=75,width=200,height=200/event-covers/ey/cfca5454-0cee-46d1-9f12-56cf097438bd.png)

Today, we're going to explore observability over our RAG Applications. [Weaviate](https://weaviate.io/) provides the retrieval and how [FriendliAI](https://friendli.ai/) provides the inference layer.

This simple example will get you started with using Weaviate and Friendli Serverless Endpoints to build a RAG system.

To use this notebook successfully, you'll need an account with FriendliAI and Weaviate.


**Note:** A Weaviate cluster is already set up, so you technically don't need to create a new cluster, and you can just READ off an existing cluster. If you want to learn more about how this cluster was set up, check out the `weaviate-embeddings-and-friendliai` dierctory in [this repository](https://github.com/weaviate/BookRecs/tree/main/data-pipeline).

You can create free accounts on all platforms.

# Set up your Environment with Comet Opik

[Comet](https://www.comet.com/) provides a hosted version of the Opik platform, simply [create a free account](https://www.comet.com/site/products/opik/) and grab you API Key from the UI.

First, we need pip install the opik and openai libraries.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U opik openai --quiet

"""Now, we'll configure Opik and FriendliAI with our respective API keys."""

import opik

opik.configure(use_local=False)

"""# FriendliAI Inference

Set up Friendli AI and get a token

1.   Head to [FriendliAI](https://friendli.ai/get-started/serverless-endpoints), and create an account.
2.   Grab a [**`FRIENDLI_TOKEN`**](https://friendli.ai/suite/setting/tokens) to use Friendli Serverless Endpoints for LLM calls.
"""

import getpass
import os

if not os.environ.get("FRIENDLI_TOKEN"):
    os.environ["FRIENDLI_TOKEN"] = getpass.getpass("Enter your Friendli Token: ")

"""Traces will now be automatically logged to the Opik UI where you can inspect the inputs, outputs, and configure evaluation metrics. After you run this cell, follow the link to the Comet UI to see you traces.

# Set up Weaviate Client

Weaviate is a vector database which supports billion scale vector search with sub 50ms query times. We'll use Weaviate to query for books in this example.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U weaviate-client --quiet

import os
import weaviate
from weaviate.classes.init import Auth
from weaviate.classes.init import AdditionalConfig, Timeout


WEAVIATE_CLUSTER_URL = os.getenv('WEAVIATE_CLUSTER_URL') or 'https://zxzyqcyksbw7ozpm5yowa.c0.us-west2.gcp.weaviate.cloud'
WEAVIATE_API_KEY = os.getenv('WEAVIATE_API_KEY') or 'n6mdfI32xrXF3DH76i8Pwc2IajzLZop2igb6' # This is a read key

weaviate_client = weaviate.connect_to_weaviate_cloud(
    cluster_url=WEAVIATE_CLUSTER_URL,
    auth_credentials=Auth.api_key(WEAVIATE_API_KEY),
    headers={"X-Friendli-Token": os.getenv('FRIENDLI_TOKEN')},
)

print(weaviate_client.is_connected())

book_collection = weaviate_client.collections.get(name="WeaviateEmbeddingBooks")

"""# Write a RAG app with Friendli, Weaviate and Opik Traces

Next, we will build a very simple LLM reasoning application and log the trace data to Opik where we can apply additional evaluation metrics and debug the LLM response.

We will use FriendliAI as our inference provider to get fast, low-cost results from open source models. In this example, we're using Friendli's serverless endpoints, which require no infrastructure setup and are ideal for quick prototyping and experimentation. Just provide the API URL endpoint as https://api.friendli.ai/serverless/v1.

For production use or personal deployments of custom models, [Friendli Dedicated Endpoints](https://friendli.ai/products/dedicated-endpoints) offers personal deployments of over 100k models on Hugging Face.

We will use Opik to collect traces to inspect the inputs and outputs of the reasoning tasks, and to create evaluation metrics for hallicinations and other common or custom issues you want to detect.

Opik integrates with OpenAI to provide a simple way to log traces for all OpenAI LLM calls. This works for all OpenAI models, including if you are using the streaming API.
"""

from opik.integrations.openai import track_openai
from openai import OpenAI

os.environ["OPIK_PROJECT_NAME"] = "rag-project" #name your project. This will appear as the project name in the Opik UI


friendli_client = OpenAI(
    base_url="https://api.friendli.ai/serverless/v1",
    api_key=os.getenv('FRIENDLI_TOKEN')
)

@opik.track
def call_llm(client, messages):
    response = friendli_client.chat.completions.create(
      model="meta-llama-3.3-70b-instruct",
      messages=messages
    )
    return response

user_query = input("What would you like to query for in the BookRecs dataset? ")

response = book_collection.query.near_text(
        query=user_query,
        limit=3
    )

for book in response.objects:
    print(book.properties['title'])

"""We are using the @opik.track decorator and the OpenAI logging integration to automatically log our traces and spans. Learn more here https://www.comet.com/docs/opik/tracing/log_traces#using-an-integration"""

@opik.track
def retrieve_context(user_query):
    # Semantic Search
    response = book_collection.query.near_text(
        query=user_query,
        limit=3
    )

    recommended_books = []
    for book in response.objects:
        recommended_books.append(book.properties['title'])
    return recommended_books

@opik.track
def generate_response(user_query, recommended_books):
  prompt = f"""
  You're a helpful assistant, reply to a chatbot message for someone inquiring for
  book recommendations. The user query was {user_query}


  These were the book that were extracted from the vector
  search:

  {recommended_books}
  """

  messages=[
      {
          "role": "user",
          "content": prompt
      }
  ]
  response = call_llm(friendli_client, messages)


  return (response.choices[0].message.content)

@opik.track(name="rag-example")
def llm_chain(user_query):
    context = retrieve_context(user_query)
    response = generate_response(user_query, context)
    return response

# Use the LLM chain
user_query = input("What types of books are you looking for? ")
result = llm_chain(user_query)
print(result)

